### ISSUE TITLE
nvidia_diagnostic_check fails with DCGM 1.6.3+

### ISSUE THREAD

**Issue by jboschee** [PBSPro/nvidia-dcgm-pbspro-connector#8]
## Expected Behavior
Executing the nvidia_diagnostic_check script should return cleanly with either a pass or a fail for the requested gpu.

## Current Behavior
For versions of DCGM 1.6.3 and later the script fails to cleanly execute with the following traceback:

Traceback (most recent call last):
  File "/opt/pbs/nvidia/PBS_scripts/nvidia_diagnostic_check", line 150, in <module>
    diagnose("gpu-diag-test", gpu_ids[i])
  File "/opt/pbs/nvidia/PBS_scripts/nvidia_diagnostic_check", line 125, in diagnose
    if (dcgm_structs.DCGM_DIAG_RESULT_PASS !=  response.blacklist):
AttributeError: 'c_dcgmDiagResponse_v4' object has no attribute 'blacklist'

## Possible Solution
Update the expected structure of the DCGM diagnostic response to operate with either the v3 structure or the v4 structure.

## Steps to Reproduce
1. Install DCGM 1.6.3 or later
2. Attempt to run nvidia_diagnostic_check for a GPU on the system

## Environment
PBSPro 19.1.3
DCGM 1.7.2
CentOS 7.7

## Detailed Description
Upon updating DCGM to the latest 1.7.2 I noticed that jobs were no longer starting on nodes running the dcgm-pbspro connector hook. Upon inspecting the mom logs for the node I came upon the traceback provided above. Rolling back versions of DCGM first to 1.7.1 and then 1.6.3 resulted in no changes. When rolling back another version to 1.5.6 functionality was restored.

Looking into what changed from 1.5.6 to 1.6.3 it appears that the response version in the DCGM python binding dcgmRunDiagnostic, called by the RunDiagnostic function, was changed from v3 to v4. 

## Possible Implementation
Fix could be accomplished by checking the returned version of the dcgmDiagResponse and if v4 walk through the levelOneResults array to check the diagnostic results returned.

**Comment by vaib** [comment]
Hi there,

thanks for pointing it out. Yes, its not been tested yet with latest dcgm version and time to time they bring about API changes resulting in this kind of issue. v1.3.3 was one such release.

I have taken note and will publish fix soon.

Thanks!

**Comment by valenbb** [comment]
Would it be possible to fix using the latest release of DCGM v1.7.2?

**Comment by vaib** [comment]
Hi There,

Yes, it's possible. We just didn't get time to test it out. Will update here, leaving the issue open,

Thanks!

**Comment by vaib** [comment]
Hi There,

We ran the connector on all versions of dcgm from v1.4 upto v1.7.2 except v1.6 because the download link for v1.6 is broken. In this course we didn't find any issue. The health check, diagnostic checks worked fine.

Can you send over mom log and information like:
default version of python installed (/bin/python)
how you run the job
do you run diagnostic_check script directly? 

We might need more info to reproduce the issue.

**Comment by valenbb** [comment]
Hi Vaib,

I was suggesting that the fix be applied to latest release of DCGM, if the issue was identified.
Thanks for verifying that no issues were found in latest release of DCGM.

-Valenbb

**Comment by jboschee** [comment]
I have attempted to run the DCGM Diagnostics routine both directly and through launching a job through PBS using the standard queue process. The system python used is Python 2.7.5.

Direct running
```
[root@se061 PBS_scripts]# /opt/pbs/nvidia/PBS_scripts/nvidia_diagnostic_check -i [[0]]
Traceback (most recent call last):
  File "/opt/pbs/nvidia/PBS_scripts/nvidia_diagnostic_check", line 150, in <module>
    diagnose("gpu-diag-test", gpu_ids[i])
  File "/opt/pbs/nvidia/PBS_scripts/nvidia_diagnostic_check", line 125, in diagnose
    if (dcgm_structs.DCGM_DIAG_RESULT_PASS !=  response.blacklist):
AttributeError: 'c_dcgmDiagResponse_v4' object has no attribute 'blacklist'
```

PBS Mom log
```
05/25/2020 10:17:45;0080;pbs_python;Hook;pbs_python;PBS_VERSION:19
05/25/2020 10:17:45;0006;pbs_python;Hook;pbs_python;Starting resource_framework_hook
05/25/2020 10:17:45;0080;pbs_python;Hook;pbs_python;nvidia_devices ['0', '1', '2', '3']
05/25/2020 10:17:45;0080;pbs_python;Hook;pbs_python;gpu_ids_by_type {'Tesla V100-SXM2-16GB': ['0', '1', '2', '3']}
05/25/2020 10:17:45;0006;pbs_python;Hook;pbs_python;In execjob_begin
05/25/2020 10:17:45;0080;pbs_python;Hook;pbs_python;In ngpus:health_check
05/25/2020 10:17:45;0080;pbs_python;Hook;pbs_python;cmd=['/opt/pbs/nvidia/PBS_scripts/nvidia_health_check']
05/25/2020 10:17:45;0080;pbs_python;Hook;pbs_python;output={"comment": "", "health": "Pass"}
05/25/2020 10:17:45;0080;pbs_python;Hook;pbs_python;err=
05/25/2020 10:17:45;0080;pbs_python;Hook;pbs_python;Pass
05/25/2020 10:17:45;0080;pbs_python;Hook;pbs_python;In ngpus:diagnostic_check
05/25/2020 10:17:45;0080;pbs_python;Hook;pbs_python;cmd=['/opt/pbs/nvidia/PBS_scripts/nvidia_diagnostic_check', '-i', '[["0", "1", "2", "3"]]']
05/25/2020 10:17:46;0080;pbs_python;Hook;pbs_python;output=
05/25/2020 10:17:46;0080;pbs_python;Hook;pbs_python;err=Traceback (most recent call last):
  File "/opt/pbs/nvidia/PBS_scripts/nvidia_diagnostic_check", line 150, in <module>
    diagnose("gpu-diag-test", gpu_ids[i])
  File "/opt/pbs/nvidia/PBS_scripts/nvidia_diagnostic_check", line 125, in diagnose
    if (dcgm_structs.DCGM_DIAG_RESULT_PASS !=  response.blacklist):
AttributeError: 'c_dcgmDiagResponse_v4' object has no attribute 'blacklist'

05/25/2020 10:17:46;0080;pbs_python;Hook;pbs_python;Diagnostic Suppressed due to DCGM issues
05/25/2020 10:17:46;0006;pbs_python;Hook;pbs_python;Hook exception:
05/25/2020 10:17:46;0006;pbs_python;Hook;pbs_python;Traceback (most recent call last):
05/25/2020 10:17:46;0006;pbs_python;Hook;pbs_python;  File "<embedded code object>", line 1872, in <module>
05/25/2020 10:17:46;0006;pbs_python;Hook;pbs_python;  File "<embedded code object>", line 1675, in execjob_begin
05/25/2020 10:17:46;0006;pbs_python;Hook;pbs_python;  File "<embedded code object>", line 527, in diagnostic_check
05/25/2020 10:17:46;0006;pbs_python;Hook;pbs_python;  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
05/25/2020 10:17:46;0006;pbs_python;Hook;pbs_python;    return _default_decoder.decode(s)
05/25/2020 10:17:46;0006;pbs_python;Hook;pbs_python;  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
05/25/2020 10:17:46;0006;pbs_python;Hook;pbs_python;    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
05/25/2020 10:17:46;0006;pbs_python;Hook;pbs_python;  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
05/25/2020 10:17:46;0006;pbs_python;Hook;pbs_python;    raise ValueError("No JSON object could be decoded")
05/25/2020 10:17:46;0006;pbs_python;Hook;pbs_python;ValueError: No JSON object could be decoded
05/25/2020 10:17:46;0006;pbs_python;Hook;pbs_python;
05/25/2020 10:17:46;0001;pbs_mom;Svr;pbs_mom;No such process (3) in get_hook_results,  Traceback (most recent call last):: no value given
05/25/2020 10:17:46;0080;pbs_mom;Req;req_reject;Reject reply code=15001, aux=0, type=5, from root@192.168.15.249:15001
05/25/2020 10:17:49;0002;pbs_python;Hook;pbs_python;configure_job: WARNING: mem_avail > vmem_avail
05/25/2020 10:17:49;0002;pbs_python;Hook;pbs_python;configure_job: Check reserve_amount and reserve_percent
05/25/2020 10:17:49;0080;pbs_python;Hook;pbs_python;Elapsed time: 0.7923
```

From digging around in the DCGM python bindings it seems the change originates in the dcgm_agent.py file. In the file in version 1.7.2 the function called by the diagnostic hook starts is:
`/usr/local/dcgm/bindings/dcgm_agent.py`
```
def dcgmRunDiagnostic(dcgm_handle, group_id, diagLevel):
    response = dcgm_structs.c_dcgmDiagResponse_v4()
    response.version = dcgm_structs.dcgmDiagResponse_version4
    fn = dcgmFP("dcgmRunDiagnostic")
    ret = fn(dcgm_handle, group_id, diagLevel, byref(response))
    dcgm_structs._dcgmCheckReturn(ret)
    return response
```
In version 1.4.6
```
def dcgmRunDiagnostic(dcgm_handle, group_id, diagLevel):
    response = dcgm_structs.c_dcgmDiagResponse_v3()
    response.version = dcgm_structs.dcgmDiagResponse_version3
    fn = dcgmFP("dcgmRunDiagnostic")
    ret = fn(dcgm_handle, group_id, diagLevel, byref(response))
    dcgm_structs._dcgmCheckReturn(ret)
    return response
```
This appears to be where the change that causes the conflict with the diagnostic script the hook uses originates.

**Comment by valenbb** [comment]
Agreed with @jboschee, I am also seeing the issue(s).

OS: Ubuntu 16.04.6 LTS
PBSPro: v18.2
Python v2.7.12 and Python v3.5.2
DCGM v1.7.2

1. Diagnostics check

root@XXXX:/opt/pbs/nvidia/PBS_scripts# ./nvidia_diagnostic_check -i [[0]]
Traceback (most recent call last):
  File "./nvidia_diagnostic_check", line 149, in <module>
    diagnose("gpu-diag-test", gpu_ids[i])
  File "./nvidia_diagnostic_check", line 124, in diagnose
    if (dcgm_structs.DCGM_DIAG_RESULT_PASS !=  response.blacklist):
AttributeError: 'c_dcgmDiagResponse_v4' object has no attribute 'blacklist'


2. PBS Mom logs:
05/26/2020 10:48:07;0006;pbs_python;Hook;pbs_python;Hook exception:
05/26/2020 10:48:07;0006;pbs_python;Hook;pbs_python;Traceback (most recent call last):
05/26/2020 10:48:07;0006;pbs_python;Hook;pbs_python;  File "<embedded code object>", line 1880, in <module>
05/26/2020 10:48:07;0006;pbs_python;Hook;pbs_python;  File "<embedded code object>", line 1566, in exechost_periodic
05/26/2020 10:48:07;0006;pbs_python;Hook;pbs_python;  File "<embedded code object>", line 395, in health_check
05/26/2020 10:48:07;0006;pbs_python;Hook;pbs_python;  File "/opt/pbs/python/lib/python2.7/json/__init__.py", line 339, in loads
05/26/2020 10:48:07;0006;pbs_python;Hook;pbs_python;    return _default_decoder.decode(s)
05/26/2020 10:48:07;0006;pbs_python;Hook;pbs_python;  File "/opt/pbs/python/lib/python2.7/json/decoder.py", line 364, in decode
05/26/2020 10:48:07;0006;pbs_python;Hook;pbs_python;    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
05/26/2020 10:48:07;0006;pbs_python;Hook;pbs_python;  File "/opt/pbs/python/lib/python2.7/json/decoder.py", line 382, in raw_decode
05/26/2020 10:48:07;0006;pbs_python;Hook;pbs_python;    raise ValueError("No JSON object could be decoded")
05/26/2020 10:48:07;0006;pbs_python;Hook;pbs_python;ValueError: No JSON object could be decoded
05/26/2020 10:48:07;0006;pbs_python;Hook;pbs_python;
05/26/2020 10:48:08;0001;pbs_mom;Svr;pbs_mom;No child processes (10) in get_hook_results,  Traceback (most recent call last):: no value given
05/26/2020 10:48:08;0100;pbs_mom;Hook;resource_framework_hook;Failed getting hook results
05/26/2020 10:48:08;0100;pbs_mom;Hook;resource_framework_hook;exechost_periodic request rejected by 'resource_framework_hook'
05/26/2020 10:48:08;0100;pbs_mom;Hook;resource_framework_hook;Exception trapped in resource_framework_hook:

Hope this helps further.

**Comment by vaib** [comment]
Let me take a look again. Will keep you posted.
